### PR TITLE
Switch to G4NP data, Collaborative Filter Backend Working

### LINKED ISSUE #66: Weird categories?
What are those?

image

### PR DESCRIPTION
**Pull request by tonypan2000**

### CODE REVIEW

**Comment by tonypan2000** [comment]
My Google Cloud Shell restarted unexpectedly while I was testing my code and some files were corrupted, including the .git folder. I managed to salvage some things from the broken files.. so this PR is a bit big with some old changes since it lost history

**Comment by tonypan2000** [comment]
But everything is working and deployable

**Comment by tonypan2000** [comment]
Resolved issue #66

**Review by iris-beckham — APPROVED** [review]
LGTM

**Pull request merged**
